name: nf-core-coproid-1.1dev
channels:
  - conda-forge
  - maxibor
  - bioconda
  - defaults
dependencies:
  - conda-forge::openblas=0.3.7
  - bioconda::adapterremoval=2.3.1
  - bioconda::bcftools=1.9
  - bioconda::bedtools=2.29.0
  - bioconda::blast=2.9.0
  - conda-forge::bokeh=1.3.4
  - bioconda::bowtie2=2.3.5
  - bioconda::damageprofiler=0.4.6
  - bioconda::fastqc=0.11.8
  - conda-forge::jupyter=1.0.0
  - bioconda::kraken2=2.0.8_beta
  - conda-forge::notebook=6.0.1
  - conda-forge::nbconvert=5.6.1
  - bioconda::nextflow=19.10.0
  - bioconda::pmdtools=0.60
  - bioconda::pysam=0.15.3
  - bioconda::samtools=1.9
  - maxibor::sourcepredict=0.4
  - conda-forge::scipy=1.3.1
  - conda-forge::matplotlib=3.1.2
  - bioconda::multiqc=1.7
  - conda-forge::r-markdown=1.1
  - conda-forge::jupyter_contrib_nbextensions=0.5.1
  - conda-forge::plotnine=0.6.0